#!/usr/bin/python
import sys

def main():
    if len(sys.argv) < 2:
        sys.exit('Missing argument')
    arg = sys.argv[1]
    if arg.endswith('lbs') or arg.endswith('kgs'):
        lbs2kgs = arg.endswith('lbs')
        magic = 2.20462
        number = arg[:-3]
        try:
            number = int(number)
        except:
            sys.exit('Fuck you')
        if lbs2kgs:
            print("%0.3f kgs" % (number * (1 / magic)))
        else:
            print("%0.3f lbs" % (number * magic))
    else:
        sys.exit('Argument must end in "kgs" or "lbs"')

main()
