#! /bin/sh

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
# bspc config focus_by_distance   true
bspc config focus_follows_pointer true

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor LVDS1 -d I II III IV
bspc monitor LVDS1 -d main www code music
bspc monitor VGA1 -d V VI VII VIII
# bspc monitor -d 一 二 三 四

bspc config focused_border_color \#586e75
bspc config normal_border_color \#073642

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

startup
panel &
