#!/bin/sh
#
# z3bra - (c) wtfpl 2014
# Fetch infos on your computer, and print them to stdout every second.
#
# Modified by Klekticist 2015

# Make room for panel
bspc config top_padding 16

clock() {
    # date '+%a %m/%d %H:%M'
    date '+%H:%M'
}

battery() {
    BATC=/sys/class/power_supply/BAT0/capacity
    BATS=/sys/class/power_supply/BAT0/status

    # Unknown here really just means charging. Not sure why my
    # computer does that
    test "`cat $BATS`" = "Unknown" && echo -n '' || echo -n ''

    sed -n p $BATC
}

volume() {
    amixer get Master | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p'
}

my_volume() {
    amixer get Master | grep Mono: | cut -d ' '  -f 6 | cut -d [ -f 2 | cut -d ] -f 1 | cut -d % -f 1
}

cpuload() {
    LINE=`ps -eo pcpu |grep -vE '^\s*(0.0|%CPU)' |sed -n '1h;$!H;$g;s/\n/ +/gp'`
    bc <<< $LINE
}

memused() {
    read t f <<< `grep -E 'Mem(Total|Free)' /proc/meminfo |awk '{print $2}'`
    bc <<< "scale=2; 100 - $f / $t * 100" | cut -d. -f1
}

network() {
    read lo int1 int2 <<< `ip link | sed -n 's/^[0-9]: \(.*\):.*$/\1/p'`
    if iwconfig $int1 >/dev/null 2>&1; then
        wifi=$int1
        eth0=$int2
    else
        wifi=$int2
        eth0=$int1
    fi
    ip link show $eth0 | grep 'state UP' >/dev/null && int=$eth0 ||int=$wifi

    #int=eth0

    ping -c 1 8.8.8.8 >/dev/null 2>&1 &&
        echo "$int connected" || echo "$int disconnected"
}

groups() {
    cur=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
    tot=`xprop -root _NET_NUMBER_OF_DESKTOPS | awk '{print $3}'`

    for w in `seq 0 $((cur - 1))`; do line="${line}="; done
    line="${line}|"
    for w in `seq $((cur + 2)) $tot`; do line="${line}="; done
    echo $line
}

nowplaying() {
    cur=`mpc current`
    # this line allow to choose whether the output will scroll or not
    test "$1" = "scroll" && PARSER='skroll -n20 -d0.5 -r' || PARSER='cat'
    test -n "$cur" && $PARSER <<< $cur || echo "- stopped -"
}

sigterm_handler() {
    bspc config top_padding 0 # Get rid of padding at top
    pkill bar # kill bar
    exit 0 # exit
}

trap 'sigterm_handler' TERM

# This loop will fill a buffer with our infos, and output it to stdout.
while :; do
    highlight="#FF859900"
    background="#FF002B36"
    foreground="#FF657B83"
    buf="%{B${background}}"
    buf="${buf}%{l}%{F${highlight}}%{F-}"
    buf="${buf} %{F${foreground}}[$(groups)]%{F-}"
    buf="${buf} %{F${highlight}}tunes:%{F-} %{F${foreground}}$(nowplaying)"%{F-}
    # buf="${buf} %{F${highlight}}NET:%{F-} %{F${foreground}}$(network) %{F-}"

    buf="${buf}%{r}"
    buf="${buf} %{F${highlight}}bat:%{F-} %{F${foreground}}$(battery)%%"%{F-}
    buf="${buf} %{F${highlight}}vol:%{F-} %{F${foreground}}$(my_volume)%%"%{F-}
    buf="${buf} %{F${highlight}}clk:%{F-} %{F${foreground}}$(clock)"%{F-}

    # buf="${buf} vol: $(my_volume)"
    echo "$buf"
    # use `nowplaying scroll` to get a scrolling output!
    sleep 1 # The HUD will be updated every second
done
